<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

In [1]:
# setup all needed modules and configurations
import numpy as np

# re-style the NumPy arrays
# remember to install needed module first:
# pip3 install numpy-html
%load_ext numpy_html

Run the cell below to enable custom style for NumPy arrays:

In [2]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1.1 Creating lists without NumPy:</b></h4>

<h4>1.1.1 List of 15 ones</h4>

In [3]:
# Define new empty list
ones_list = []

# Populate list with 15 ones
for i in range(15):
    ones_list.append(1)

# Print list
ones_list

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

<h4>1.1.2 List of 15 number 7's</h4>

In [4]:
# Define new empty list
sevens_list = []

# Populate list with 15 sevens
for j in range(15):
    sevens_list.append(7)

# Print list
sevens_list

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

<h4>1.1.3 List of numbers from 100 to 150</h4>

In [5]:
# Define new empty list
numbers_list = []

# Populate list with numbers between 100..150
for x in range(100, 151):
    numbers_list.append(x)

# Print list
numbers_list

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

<h4>1.1.4 List of even numbers between 0 and 100</h4>

In [6]:
# Define new empty list
evens_list = []

# Populate list with even numbers between 0..100
for y in range(0, 101):
    if y % 2 == 0:
        evens_list.append(y)

# Print list
evens_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

<h4>1.1.5 List of years that are divisible by 4 between 1950 and 2020</h4>

In [7]:
# Define new empty list
years_list = []

# Populate list with years that are divisible by 4 between 1950 and 2020
for x in range(1950, 2021):
    if x % 4 == 0:
        years_list.append(x)

# Print list
years_list

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>1.2	Arrays created with NumPy:</b></h4>



<h4>1.2.1 Array of 15 zeroes</h4>

In [8]:
# Create array of 15 zeros
np.zeros(15, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<h4>1.2.2 Array of 15 ones</h4>

In [9]:
# Create array of 15 ones
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h4>1.2.3 Array of 15 number 7's</h4>

In [10]:
# Create array of 15 sevens
np.full(15, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

<h4>1.2.4 Array of numbers from 100 to 150</h4>

In [11]:
# Create array of numbers between 100..150
np.arange(100, 151, 1)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

<h4>1.2.5 Array of numbers from 1900 to 2021</h4>

In [12]:
# Create array of numbers between 1900..2021
np.arange(1900, 2022, 1)

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

<h4>1.2.6 Array of even numbers between 0 and 100</h4>

In [13]:
# Create array of even numbers between 0..100
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

<h4>1.2.7  Array of years that are divisible by 4 between 1950 and 2020</h4>

In [14]:
# Create array of numbers between 1950..2020
years = np.arange(1950, 2021)

# Filter numbers that are divisible by 4
div_four = years[years % 4 == 0]

# Print filtered array
div_four

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4>Comment about Numpy vs. lists</h4>
- Creating arrays with numpy is much easier. Last task was just first to create array data and then filter it. Othervice much simpler than without numpy.

<h3><b>1.3 NumPy vectors and matrices:</b></h3>


<h4>1.3.1 Create a NumPy vector (list) containing these values:<br>
<i>5, 16, 9, 2, 19, 18, 11, 7</i><br></h4>

In [15]:
# Define vector items
items = [5, 16, 9, 2, 19, 18, 11, 7]

# Create Numpy vector form items
vector_list = np.array(items)

# Use argmax() to find the position index of the largest value in the vector, and print it
np.argmax(vector_list)


4

<h4>1.3.2 Create a 7x7 matrix, with values from 1 to 49</h4>

In [16]:
np.arange(1, 50, 1).reshape(7, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

<h4>1.3.2.E Create a 7x7 matrix, with values from 1 to 49 (list of lists) without NumPy in Python</h4>

In [17]:
# Initialize empty list
a = []

# Outer loop of range 1..8
for i in range(1, 8): 
    # Inner list to store inner loop items  
    b = []
    # Inner loop of range 1..8
    for j in range(1, 8):
        # Append numbers to inner list, multiply by 7 and outer loop number
        b.append(j + 7 * i - 7)
    # Append inner loop list to list a
    a.append(b)

# Print list (matrix)
a


[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

<h4>1.3.3 Generate 8x8 random number matrix, values between 0 and 5</h4>

In [18]:
np.random.default_rng().integers(6, size=(8,8))

array([[1, 4, 3, 4, 3, 4, 5, 0],
       [1, 0, 1, 0, 0, 2, 4, 5],
       [0, 2, 3, 4, 4, 3, 0, 3],
       [2, 1, 0, 0, 2, 5, 4, 5],
       [0, 4, 0, 0, 3, 2, 5, 0],
       [4, 0, 3, 0, 1, 1, 2, 2],
       [3, 4, 2, 5, 4, 1, 2, 3],
       [5, 0, 5, 4, 1, 4, 0, 2]], dtype=int64)

<h4>1.3.3 Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)</h4>

In [19]:
# Using Legacy Generator (frozen, no further inprovements from NumPy > v1.16)
np.random.randn(8,8)

array([[ 0.21114933, -1.16995624,  0.29495724,  0.21662062, -0.34777684,
         1.50991215, -0.16732736,  0.50458174],
       [ 0.54838134, -1.37949495, -1.13251095,  0.16555014, -0.26579395,
        -0.09172695, -0.74895273,  0.85720182],
       [ 0.37759565, -0.62156328,  0.3276994 , -0.84216158,  1.434355  ,
         0.89136682,  0.20292583, -0.24959251],
       [-0.45066532, -0.77587252, -0.90151526, -1.3403279 ,  0.26530153,
        -0.54875407, -0.31924366, -0.6182179 ],
       [ 0.7579646 ,  0.98609272,  0.0311729 , -1.36554744,  0.4462821 ,
        -1.21378591, -0.10618276, -1.46988515],
       [ 1.74165383, -0.6826913 , -0.65204085,  0.33637478, -0.70790597,
        -1.37132477,  0.98967063, -0.1924356 ],
       [ 0.18750823, -0.67265495, -0.58787304, -0.64691768, -0.15267506,
        -1.32728629,  0.55499041, -0.31834349],
       [ 0.31341878,  1.1408333 ,  1.24708658,  0.04328775,  0.51063509,
         0.83909365, -0.75539061,  1.42850786]])

In [20]:
# Using Random Generator (from NumPy > v1.16)
np.random.default_rng().standard_normal(size=(8, 8))

array([[-1.87773881,  1.21635622,  0.831104  , -0.3664478 ,  0.38336064,
        -0.59362015, -1.07060346,  1.56441408],
       [ 0.47673589, -2.69155443,  0.660002  ,  1.21003917, -0.81937507,
        -1.04306629,  0.51991969,  0.55496063],
       [ 0.97764902,  2.43876209,  0.31222124,  0.59919328,  0.17364702,
        -0.12960957,  0.52804797,  2.17027727],
       [ 0.76143949,  0.6898684 , -0.28693331,  0.14559403,  1.17556063,
        -0.22756648,  0.22472892,  1.76998414],
       [-0.75141501,  1.52772097,  0.40387835,  0.21626601, -0.15134195,
         2.16638841, -0.84165926,  0.32183915],
       [-0.34372946,  0.85977597,  0.58894507,  0.55164863, -0.24058005,
         1.45615255, -0.08781686,  0.05084675],
       [ 1.13849356, -0.07211112,  2.1759585 ,  1.63749929,  0.20263492,
         1.01573687, -0.5488097 ,  2.60838717],
       [-0.66142954, -0.6742444 ,  0.76731327, -0.3267777 , -0.46338527,
         1.89579201,  0.99876081,  0.22346695]])

<h3><b>1.4 Linearly spaced arrays </b></h3>


<h4>1.4.1 Array (list/vector) of 10 values between value 0 and 1</h4>

In [21]:
# Create array of linearly space of 10 values
np.linspace(0, 1, 10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

<h4>1.4.2 10x10 matrix between values 0 and 5</h4>

In [22]:
np.linspace(0, 5, 100).reshape(10, 10)

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

<h4>1.4.2.E 10x10 matrix between values 0 and 5 without NumPy</h4>

In [23]:
# Define empty list
matrix_a = []
# Define step between values
step = 5 / 99
sice = 10
# Outer loop
for i in range(sice):
    # Define empty list
    matrix_b = []
    # Inner loop
    for j in range(sice):
        # Calculate each number value
        value = i * sice * step + j * step
        # Append each value to matrix_b and round it to 8 digits
        matrix_b.append(round(value, 8))
    # Append inner loop matrix to matrix_a
    matrix_a.append(matrix_b)
# Print matrix_a
matrix_a

[[0.0,
  0.05050505,
  0.1010101,
  0.15151515,
  0.2020202,
  0.25252525,
  0.3030303,
  0.35353535,
  0.4040404,
  0.45454545],
 [0.50505051,
  0.55555556,
  0.60606061,
  0.65656566,
  0.70707071,
  0.75757576,
  0.80808081,
  0.85858586,
  0.90909091,
  0.95959596],
 [1.01010101,
  1.06060606,
  1.11111111,
  1.16161616,
  1.21212121,
  1.26262626,
  1.31313131,
  1.36363636,
  1.41414141,
  1.46464646],
 [1.51515152,
  1.56565657,
  1.61616162,
  1.66666667,
  1.71717172,
  1.76767677,
  1.81818182,
  1.86868687,
  1.91919192,
  1.96969697],
 [2.02020202,
  2.07070707,
  2.12121212,
  2.17171717,
  2.22222222,
  2.27272727,
  2.32323232,
  2.37373737,
  2.42424242,
  2.47474747],
 [2.52525253,
  2.57575758,
  2.62626263,
  2.67676768,
  2.72727273,
  2.77777778,
  2.82828283,
  2.87878788,
  2.92929293,
  2.97979798],
 [3.03030303,
  3.08080808,
  3.13131313,
  3.18181818,
  3.23232323,
  3.28282828,
  3.33333333,
  3.38383838,
  3.43434343,
  3.48484848],
 [3.53535354,
  3.585858

<h3><b>1.5 Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


<h4>1.5.1 3x5 matrix</h4>

In [24]:
# Create numbers list
numbers = [23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]
# Convert list to matrix
np.array(numbers).reshape(3, 5)


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

<h4>1.5.2 Generate NumPy array as shown above</h4>

In [25]:
np.arange(128, 256, 1).reshape(8, 16)


array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<h4>1.5.3 Generate NumPy array as shown above</h4>

In [26]:
np.arange(0.05, 5.05, 0.05).reshape(10, 10)

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>1.6 Matrix</b></h3>


<h4>1.6.1 Matrix slicing</h4>

In [27]:
# exercise 1.6.1, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h4>1.6.2 Matrix slicing</h4>

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [28]:
# exercise 1.6.2, matrix slicing
slice_data = dataset[3:, 2:]
slice_data


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

<h4>1.6.3 Matrix slicing</h4>

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [29]:
# exercise 1.6.3, matrix slicing
slice_data2 = dataset[:4, 3]
slice_data2


array([ 4, 10, 16, 22])

<h4>1.6.4 Matrix slicing</h4>

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [30]:
# exercise 1.6.4, matrix slicing
slice_data3 = dataset[2]
slice_data3

array([13, 14, 15, 16, 17, 18])

<h4>1.6.5 Matrix slicing</h4>

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [31]:
# exercise 1.6.5, matrix slicing
slice_data4 = dataset[3:]
slice_data4

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>1.7 Matrix dataset</b></h3>


<h4>1.7.1 Add 50 to all values in the array (use broadcasting)</h4>

In [32]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)

# Broadcast all values to 50
dataset_2 = dataset_2 + 50
dataset_2


array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

<h4>1.7.2 Get the sum of all values in the dataset</h4>

In [33]:
data_sum = np.sum(dataset_2)
data_sum

3675

<h4>1.7.3 Get sum of only odd numbers in the dataset</h4>

In [34]:
odd_data = dataset_2[dataset_2 % 2 != 0]
np.sum(odd_data)

1875

<h4>1.7.4 Get the standard deviation of the values in the datasett</h4>

In [35]:
np.std(dataset_2)

14.142135623730951

<h4>1.7.5 Get the sum of all values by ROW in the dataset</h4>

In [36]:
np.sum(dataset_2, axis=1)

array([378, 427, 476, 525, 574, 623, 672])

<h4>1.7.6  Get the sum of all values by COLUMN in the dataset</h4>

In [37]:
np.sum(dataset_2, axis=0)

array([504, 511, 518, 525, 532, 539, 546])

<h4>1.7.E  Same as 1.7.1 to 1.7.6 but without NumPy</h4>

In [38]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)

# Add value 50 to all dataset items
for i in range(len(dataset_2)):
    for j in range(len(dataset_2[i])):
        dataset_2[i][j] += 50

dataset_2

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [39]:
# Sum of all values in dataset
all_sum = 0

for i in range(7):
    for j in range(7):
        all_sum += dataset_2[i][j]

all_sum

3675

In [40]:
# Sum of all odd values in dataset
odd_sum = 0

for i in range(7):
    for j in range(7):
        item = dataset_2[i][j]
        if item % 2 != 0:
            odd_sum += item

odd_sum

1875

<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix



<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [41]:
# advanced extra exercise 2
matrix_d = np.arange(0, 50).reshape(5, 10)
matrix_d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
# Define set
pos_added = set()

# Do while pos_added has 10 items
while len(pos_added) < 10:
    row = np.random.randint(0, 4)
    col = np.random.randint(0, 9)
    pos = (row, col)

    # Check if random [row, col] is in pos_added
    if pos not in pos_added:
        matrix_d[row, col] = np.random.randint(-100, -3)
        pos_added.add(pos)

matrix_d

array([[-44,   1,   2,   3, -20,   5, -77,   7,   8,   9],
       [ 10,  -9,  12,  13, -67,  15,  16, -67,  18,  19],
       [-94,  21, -56,  23,  24,  25,  26,  27,  28,  29],
       [-88,  31,  32,  33,  34,  35, -48,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [43]:
# Import masked array
import numpy.ma as ma

In [44]:
# Use masked array to replace off (minus) range values with 0
matrix_d = ma.masked_less(matrix_d, 0)
matrix_d

masked_array(
  data=[[--, 1, 2, 3, --, 5, --, 7, 8, 9],
        [10, --, 12, 13, --, 15, 16, --, 18, 19],
        [--, 21, --, 23, 24, 25, 26, 27, 28, 29],
        [--, 31, 32, 33, 34, 35, --, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],
  mask=[[ True, False, False, False,  True, False,  True, False, False,
         False],
        [False,  True, False, False,  True, False, False,  True, False,
         False],
        [ True, False,  True, False, False, False, False, False, False,
         False],
        [ True, False, False, False, False, False,  True, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False]],
  fill_value=999999)

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [45]:
# advanced extra exercise 3


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [46]:
# advanced extra exercise 4
