<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

In [1]:
# setup all needed modules and configurations
import numpy as np

# re-style the NumPy arrays
# remember to install needed module first:
# pip3 install numpy-html
%load_ext numpy_html

Run the cell below to enable custom style for NumPy arrays:

In [2]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<h4>1.1 List of 15 ones</h4>

In [3]:
# Define new empty list
ones_list = []

# Populate list with 15 ones
for i in range(15):
    ones_list.append(1)

# Print list
ones_list

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

<h4>1.2 List of 15 number 7's</h4>

In [4]:
# Define new empty list
sevens_list = []

# Populate list with 15 sevens
for j in range(15):
    sevens_list.append(7)

# Print list
sevens_list

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

<h4>1.3 List of numbers from 100 to 150</h4>

In [5]:
# Define new empty list
numbers_list = []

# Populate list with numbers between 100..150
for x in range(100, 151):
    numbers_list.append(x)

# Print list
numbers_list

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

<h4>1.4 List of even numbers between 0 and 100</h4>

In [6]:
# Define new empty list
evens_list = []

# Populate list with even numbers between 0..100
for y in range(0, 101):
    if y % 2 == 0:
        evens_list.append(y)

# Print list
evens_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

<h4>1.5 List of years that are divisible by 4 between 1950 and 2020</h4>

In [7]:
# Define new empty list
years_list = []

# Populate list with years that are divisible by 4 between 1950 and 2020
for x in range(1950, 2021):
    if x % 4 == 0:
        years_list.append(x)

# Print list
years_list

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



<h4>2.1 Array of 15 zeroes</h4>

In [8]:
# Create array of 15 zeros
np.zeros(15, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<h4>2.2 Array of 15 ones</h4>

In [9]:
# Create array of 15 ones
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h4>2.3 Array of 15 number 7's</h4>

In [10]:
# Create array of 15 sevens
np.full(15, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

<h4>2.4 Array of numbers from 100 to 150</h4>

In [11]:
# Create array of numbers between 100..150
np.arange(100, 151, 1)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

<h4>2.5 Array of numbers from 1900 to 2021</h4>

In [12]:
# Create array of numbers between 1900..2021
np.arange(1900, 2022, 1)

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

<h4>2.6 Array of even numbers between 0 and 100</h4>

In [13]:
# Create array of even numbers between 0..100
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

<h4>2.7  Array of years that are divisible by 4 between 1950 and 2020</h4>

In [14]:
# Create array of numbers between 1950..2020
years = np.arange(1950, 2021)

# Filter numbers that are divisible by 4
div_four = years[years % 4 == 0]

# Print filtered array
div_four

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4>Comment about Numpy vs. lists</h4>
- Creating arrays with numpy is much easier. Last task was just first to create array data and then filter it. Othervice much simpler than without numpy.

<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [15]:
# exercise 1.3, NumPy vectors and matrices
# use different variable names for each subtask
# you can also make new code cells if you need


<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [16]:
# exercise 1.4, linspace
# use different variable names for each subtask
# you can also make new code cells if you need


<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [17]:
# exercise 1.5a, create matrix


- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [18]:
# exercise 1.5b, generate NumPy array / matrix


- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [19]:
# exercise 1.5c, generate NumPy array / matrix


<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [20]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [21]:
# exercise 1.6b, matrix slicing


- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [22]:
# exercise 1.6c, matrix slicing


- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [23]:
# exercise 1.6d, matrix slicing

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [24]:
# exercise 1.6e, matrix slicing

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python!

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [25]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)

# use different variable names for each subtask
# you can also make new code cells if you need


<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [26]:
# advanced extra exercise 1


<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [27]:
# advanced extra exercise 2


<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [28]:
# advanced extra exercise 3


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [29]:
# advanced extra exercise 4
